# Generated by Django 3.2.7 on 2021-09-26 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryItem',
            fields=[
                ('primary_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('primary_item_name', models.CharField(max_length=128, verbose_name='大項目名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'db_table': 'primary_items',
            },
        ),
        migrations.CreateModel(
            name='SecondaryItem',
            fields=[
                ('secondary_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('secondary_item_name', models.CharField(max_length=128, verbose_name='中項目名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('primary_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.primaryitem', verbose_name='大項目名')),
            ],
            options={
                'db_table': 'secondary_items',
            },
        ),
        migrations.CreateModel(
            name='TertiaryItem',
            fields=[
                ('tertiary_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tertiary_item_name', models.CharField(max_length=128, verbose_name='中項目名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('secondary_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.secondaryitem', verbose_name='中項目名')),
            ],
            options={
                'db_table': 'tertiary_items',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wallet_name', models.CharField(max_length=128, verbose_name='出金元名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transaction_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type_name', models.CharField(max_length=128, verbose_name='取引種別名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'db_table': 'transaction_types',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_at', models.DateTimeField(verbose_name='取引日')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='取引金額')),
                ('note', models.CharField(blank=True, max_length=128, verbose_name='備考')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='数量')),
                ('quantity_unit', models.CharField(blank=True, max_length=128, verbose_name='数量単位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('primary_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.primaryitem', verbose_name='大項目名')),
                ('secondary_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.secondaryitem', verbose_name='中項目名')),
                ('tertiary_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.tertiaryitem', verbose_name='小項目名')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactiontype', verbose_name='取引種別名')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.wallet', verbose_name='出金元')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('budget_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('budget_period_start_at', models.DateField(verbose_name='予算開始日')),
                ('budget_period_end_at', models.DateField(verbose_name='予算終了日')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='予算金額')),
                ('note', models.CharField(blank=True, max_length=128, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('primary_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.primaryitem', verbose_name='大項目名')),
                ('secondary_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.secondaryitem', verbose_name='中項目名')),
                ('tertiary_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.tertiaryitem', verbose_name='小項目名')),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('balance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='残高金額')),
                ('receipt_date', models.DateTimeField(verbose_name='記帳日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.wallet', verbose_name='出金元')),
            ],
            options={
                'db_table': 'balances',
            },
        ),
    ]
